# Generated by Django 5.1.6 on 2025-02-17 10:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(150)])),
            ],
        ),
        migrations.CreateModel(
            name='Targeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('ALL', 'All')], null=True)),
                ('age_from', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('age_to', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('location', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('impressions_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('impressions_count', models.IntegerField(default=0)),
                ('clicks_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('clicks_count', models.IntegerField(default=0)),
                ('cost_per_impression', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_per_click', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ad_title', models.CharField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(150)])),
                ('ad_text', models.CharField(validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(500)])),
                ('start_date', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('end_date', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=False)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisers.advertiser')),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_campaign', to='advertisers.campaign')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_client', to='clients.client')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='clicks',
            field=models.ManyToManyField(related_name='campaign_clicks', through='advertisers.Click', to='clients.client'),
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impression_campaign', to='advertisers.campaign')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impression_client', to='clients.client')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='impressions',
            field=models.ManyToManyField(related_name='campaign_impressions', through='advertisers.Impression', to='clients.client'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='targeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisers.targeting'),
        ),
    ]
