# Generated by Django 5.1.6 on 2025-02-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='cost',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impression',
            name='cost',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
