# Generated by Django 5.1.6 on 2025-02-17 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0002_click_cost_impression_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='cost_per_click',
            field=models.DecimalField(decimal_places=5, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cost_per_impression',
            field=models.DecimalField(decimal_places=5, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='click',
            name='cost',
            field=models.DecimalField(decimal_places=5, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='impression',
            name='cost',
            field=models.DecimalField(decimal_places=5, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
