# Generated by Django 5.1.6 on 2025-02-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0003_alter_campaign_cost_per_click_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
