# Generated by Django 5.1.6 on 2025-02-21 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0005_alter_advertiser_name_alter_campaign_ad_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='cost_per_click',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cost_per_impression',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='click',
            name='cost',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='impression',
            name='cost',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
