global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: "/metrics/metrics"
    static_configs:
      - targets:
        - app:8080
        - localhost:8080
